runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(index.html)?
  static_files: index.html
  upload: index.html
- url: /static
  static_dir: static
- url: /.*
  script: app.flask_app.app

libraries:
- name: ssl
  version: latest
- name: numpy
  version: "1.6.1"